./exe/MicroNTupleMaker user.ebusch.364702.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ2WithSW.mc16a_tree /eos/atlas/atlascerngroupdisk/phys-exotics/jdm/svjets-schannel/v1.0/multijet/
./exe/MicroNTupleMaker user.ebusch.364702.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ2WithSW.mc16d_tree /eos/atlas/atlascerngroupdisk/phys-exotics/jdm/svjets-schannel/v1.0/multijet/
./exe/MicroNTupleMaker user.ebusch.364702.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ2WithSW.mc16e_tree /eos/atlas/atlascerngroupdisk/phys-exotics/jdm/svjets-schannel/v1.0/multijet/
./exe/MicroNTupleMaker user.ebusch.364703.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ3WithSW.mc16a_tree /eos/atlas/atlascerngroupdisk/phys-exotics/jdm/svjets-schannel/v1.0/multijet/
./exe/MicroNTupleMaker user.ebusch.364703.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ3WithSW.mc16d_tree /eos/atlas/atlascerngroupdisk/phys-exotics/jdm/svjets-schannel/v1.0/multijet/
./exe/MicroNTupleMaker user.ebusch.364703.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ3WithSW.mc16e_tree /eos/atlas/atlascerngroupdisk/phys-exotics/jdm/svjets-schannel/v1.0/multijet/
./exe/MicroNTupleMaker user.ebusch.364704.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ4WithSW.mc16a_tree /eos/atlas/atlascerngroupdisk/phys-exotics/jdm/svjets-schannel/v1.0/multijet/
./exe/MicroNTupleMaker user.ebusch.364704.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ4WithSW.mc16d_tree /eos/atlas/atlascerngroupdisk/phys-exotics/jdm/svjets-schannel/v1.0/multijet/
./exe/MicroNTupleMaker user.ebusch.364704.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ4WithSW.mc16e_tree /eos/atlas/atlascerngroupdisk/phys-exotics/jdm/svjets-schannel/v1.0/multijet/
